---
# tasks file for systemd
- name: fake ansible managed line
  lineinfile:
    path: /etc/systemd/system.conf.d/local.conf
    insertbefore: BOF
    regexp: '^# Ansible managed'
    line: "# Ansible managed. role: {{ role_name }}."
    state: present
  when:
    - systemd_config is defined
  tags:
    - systemd
    - config
    - conf.d

- name: system.conf.d/local.conf
  community.general.ini_file:
    mode: 0664
    owner: root
    group: root
    no_extra_spaces: true
    path: /etc/systemd/system.conf.d/local.conf
    section: Manager
    option: "{{ item.0 }}"
    value: "{{ item.1 }}"
  loop: "{{ systemd_config | dictsort }}"
  when:
    - systemd_config is defined
  tags:
    - systemd
    - config
    - conf.d

- name: masked units
  systemd:
    name: "{{ item.name }}"
    masked: "{{ item.masked }}"
  loop: "{{ systemd_units }}"
  when:
    - systemd_units is defined
    - systemd_units | length
  tags:
    - systemd
    - units
