---
# handlers file for systemd
- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Systemd service restart
  ansible.builtin.service:
    name: "{{ item.item.name }}"
    state: restarted
  loop: "{{ s.results }}"
  when: item.changed

- name: Systemd restarter service restart
  ansible.builtin.service:
    name: "{{ item.item.name }}-restart"
    state: restarted
  loop: "{{ r.results }}"
  when: item.changed

- name: Systemd restarter path restart
  ansible.builtin.service:
    name: "{{ item.item.name }}-restart.path"
    state: restarted
  loop: "{{ p.results }}"
  when: item.changed
